name: babi_cakes_mobile
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  get: ^4.6.5
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_otp_text_field: ^1.1.1
  fluttertoast: ^8.1.1
  http: ^0.13.5
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.15
  local_auth: ^2.1.2
  tab_indicator_styler: ^1.0.0
  flutter_svg: ^0.19.3
  shimmer: ^2.0.0
  brasil_fields: 1.6.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - assets/images/dashboard/
    - assets/images/splash_images/
    - assets/images/welcome_images/
    - assets/images/forget_password/
    - assets/images/on_boarding_images/
    - assets/icons/
    - assets/icons/bottom/
    - assets/icons/ordenation/
    - assets/images/
    - assets/images/categorys/

  fonts:
    - family: "Nunito Sans"
      fonts:
        - asset: assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-200i.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-300i.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-400i.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-600i.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-700i.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-800i.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-900i.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-200.ttf
          weight: 200
        - asset: assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-300.ttf
          weight: 300
        - asset: assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-400.ttf
          weight: 400
        - asset: assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-600.ttf
          weight: 600
        - asset: assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-700.ttf
          weight: 700
        - asset: assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-800.ttf
          weight: 800
        - asset: assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-900.ttf
          weight: 900

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
